### ISSUE TITLE
[SWIFT][ceph] error pushing to the registry, unable to parse time error

### ISSUE THREAD

**Issue by gschukin** [docker/distribution#1673]
I'm tring to setup latest release (also tried master) with ceph Firefly as storage backend and swift driver. Unfortuantely i'm facing this error in registry logs with failed push.
```
time="2016-04-26T14:39:46.782197286Z" level=debug msg="swift.Writer(\"/docker/registry/v2/repositories/redis/_uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516/data\", true)" environment=development go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=1e3ec34b-fbb1-4c65-8ec2-29c0bcc22923 http.request.method=PATCH http.request.remoteaddr="172.17.42.1:43162" http.request.uri="/v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry trace.duration=89.284371ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Writer" trace.id=bfe65d69-86b6-45c2-be44-778c4d6700d9 trace.line=124 vars.name=redis vars.uuid=47066a4f-d75d-4718-954a-aa4b9f0f4516 version=v2.4.0 
time="2016-04-26T14:39:46.782280848Z" level=error msg="error resolving upload: swift: parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"" environment=development go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=1e3ec34b-fbb1-4c65-8ec2-29c0bcc22923 http.request.method=PATCH http.request.remoteaddr="172.17.42.1:43162" http.request.uri="/v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry vars.name=redis vars.uuid=47066a4f-d75d-4718-954a-aa4b9f0f4516 version=v2.4.0 
time="2016-04-26T14:39:46.782363118Z" level=error msg="response completed with error" environment=development err.code=unknown err.detail="swift: parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"" err.message="unknown error" go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=1e3ec34b-fbb1-4c65-8ec2-29c0bcc22923 http.request.method=PATCH http.request.remoteaddr="172.17.42.1:43162" http.request.uri="/v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=180.236063ms http.response.status=500 http.response.written=202 instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry vars.name=redis vars.uuid=47066a4f-d75d-4718-954a-aa4b9f0f4516 version=v2.4.0 
172.17.42.1 - - [26/Apr/2016:14:39:46 +0000] "PATCH /v2/redis/blobs/uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516?_state=bJkXKAxxvr0H0CH3TS_XmSwunVUeY_cClIaw_7qS_6F7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiI0NzA2NmE0Zi1kNzVkLTQ3MTgtOTU0YS1hYTRiOWYwZjQ1MTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMDQtMjZUMTQ6Mzk6NDUuODk0OTQ1NDI1WiJ9 HTTP/1.1" 500 202 "" "docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))"
time="2016-04-26T14:39:46.786419096Z" level=debug msg="authorizing request" environment=development go.version=go1.6.1 http.request.host="localhost:5000" http.request.id=5a53f9ff-ce45-40cb-aa2f-6e3663e1117b http.request.method=HEAD http.request.remoteaddr="172.17.42.1:43178" http.request.uri="/v2/redis/blobs/sha256:3526e56c913b13dd4173467dac44138d98fca5c50d0dbeff28657112035c89ec" http.request.useragent="docker/1.11.1-rc1 go/go1.5.4 git-commit/c90c70c kernel/3.16.0-38-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1-rc1 \\(linux\\))" instance.id=b095a5bd-fb6a-4c3b-b921-b9f819ac2219 service=registry vars.digest="sha256:3526e56c913b13dd4173467dac44138d98fca5c50d0dbeff28657112035c89ec" vars.name=redis version=v2.4.0 
```

```
docker version
Client:
 Version:      1.11.1-rc1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   c90c70c
 Built:        Tue Apr 26 04:55:03 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1-rc1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   c90c70c
 Built:        Tue Apr 26 04:55:03 2016
 OS/Arch:      linux/amd64
```
```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.1-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-38-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.785 GiB
Name: gleb-virtual-machine
ID: 6LNL:2GXT:LRXG:UG32:ZXAL:WGYR:OZ2B:XIOK:WGJF:AOG2:RH5S:3GFR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

I also tried different versions of Docker but the issue still exists.

Registry config
```
version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: development
storage:
  swift:
    username: REMOVED
    password: REMOVED
    authurl: REMOVED
    tenantid: REMOVED
    insecureskipverify: false
    container: DockerDistribution
    rootdirectory: /registry
  delete:
    enabled: true
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
  redirect:
    disable: false
http:
    addr: :5000
    secret: 530cceaef4af43b989405690f067d7ae
    headers:
        X-Content-Type-Options: [nosniff]
redis:
  addr: 10.16.208.6:6379
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
```

**Comment by gschukin** [comment]
The root cause is that ceph doest't return any metada for the
```
/docker/registry/v2/repositories/redis/_uploads/47066a4f-d75d-4718-954a-aa4b9f0f4516/data
```
object. And failing I suppose here https://github.com/docker/distribution/blob/master/vendor/github.com/ncw/swift/swift.go#L1741

Also verified this with Java SDK.

But I didn't find a way how to create such invalid object in ceph by myself. No matter how all my objects appear to be a valid one in terms of metadata.

**Comment by gschukin** [comment]
Tried 2.3.1 - DLO manifests created successfully and have all proper metadata

**Comment by gschukin** [comment]
Fixed by adding a check for absent "Last-Modified" header in swift driver
```
if resp.Header.Get("Last-Modified") != "" {
````
after line https://github.com/docker/distribution/blob/master/vendor/github.com/ncw/swift/swift.go#L1739

**Comment by RichardScothern** [comment]
@gschukin what is the implication of not setting `info.ServerLastModified` ?

**Comment by gschukin** [comment]
I didn't observe any side effects in my tests. Thus I assume that this is solely Ceph RadosGW bug, as it  must return this header for any requests.

I'm running stress test now, no errors for push requests. Going to run pull tests tommorow - ~200 docker clients permanetly pulling containers.

**Comment by RichardScothern** [comment]
Understood. Could this have been fixed in a more recent Ceph version?

Also, if your tests pan out, could you PR? 😺

**Comment by gschukin** [comment]
@RichardScothern I'll talk to my vendor to check this out, if not fixed already they will submit PR to Ceph.

Sure, should I submit PR to Distribution repo or to ncw/swift one?

**Comment by RichardScothern** [comment]
If you submit a PR to this repository, the fix can be released in 2.4.1 to unblock you.

If it's an upstream bug, we should create an issue in the correct repository (it appears ceph is the culprit here)

**Comment by gschukin** [comment]
OK.

BTW if you would like to gather any information from my stress tests, let me know. Right now I'm on master branch plus #1626

**Comment by gschukin** [comment]
@RichardScothern saw lots of these errors
```
time="2016-04-27T23:28:09.057049726Z" level=error msg="error connecting to redis instance 10.16.208.6:6379: dial tcp 10.16.208.6:6379: i/o timeout" environment=development go.version=go1.6.2 instance.id=7bccd430-0a9b-4d43-ba26-b79f8e4b2b44 service=registry version=v2.3.0-rc.1-257-g47d1455.m 
time="2016-04-27T23:28:09.057389112Z" level=error msg="redis: error connecting: dial tcp 10.16.208.6:6379: i/o timeout" environment=development go.version=go1.6.2 instance.id=7bccd430-0a9b-4d43-ba26-b79f8e4b2b44 redis.connect.duration=10.630681ms service=registry version=v2.3.0-rc.1-257-g47d1455.m 
time="2016-04-27T23:28:09.05747451Z" level=error msg="error adding descriptor sha256:4618fb10d2549192460031b9eb9d9f5b06fe2174d41af576f6c0a7cc2e13657c to cache: dial tcp 10.16.208.6:6379: i/o timeout" environment=development go.version=go1.6.2 http.request.host="10.16.208.7:5000" http.request.id=c6dd2bbd-0011-49a0-8771-5af82e20aa6a http.request.method=GET http.request.remoteaddr="10.16.209.47:49756" http.request.uri="/v2/ezpublish5/blobs/sha256:4618fb10d2549192460031b9eb9d9f5b06fe2174d41af576f6c0a7cc2e13657c" http.request.useragent="docker/1.10.3 go/go1.5.4 git-commit/8acee1b kernel/4.5.2-coreos os/linux arch/amd64" instance.id=7bccd430-0a9b-4d43-ba26-b79f8e4b2b44 service=registry vars.digest="sha256:4618fb10d2549192460031b9eb9d9f5b06fe2174d41af576f6c0a7cc2e13657c" vars.name=ezpublish5 version=v2.3.0-rc.1-257-g47d1455.m
```

And almost run out of memory:

![image](https://cloud.githubusercontent.com/assets/1642745/14871258/3ea03162-0ce9-11e6-90d3-f19f5f8460dc.png)

Around 200 pull requests.

**Comment by RichardScothern** [comment]
interesting @gschukin 

Can you grab the memory statistics from `http://localhost:5001/debug/pprof/heap` (with your host and debug server port).

**Comment by gschukin** [comment]
@RichardScothern Done

you can find it here https://gist.github.com/gschukin/7a630c7edf5ce7ad9be5c4e3b1d2f137
Grabbed it before test, in the middle, right after the test and 15 minutes after the test

**Comment by RichardScothern** [comment]
I had a quick look at these yesterday, the results were not too helpful.  What is the commit hash for the binary you use?  (I need it for the symbol lookup).

**Comment by gschukin** [comment]
It's a1d7463d67bcf6ee87b7bd6bbcc3aeacf02e2d52 with small chages to swift driver and manual merge from alpine PR
Full source code is here https://drive.google.com/open?id=0Bxnzlm4Zl0mARE96YTRRRW5waFk

**Comment by gschukin** [comment]
@RichardScothern this is indeed ceph bug http://tracker.ceph.com/issues/15812
Currently it affects any version of ceph. I'll submit PR shortly.

**Comment by RichardScothern** [comment]
PR merged.  Closing.

**Comment by sunil3s3** [comment]
@gschukin, Please let me what check did you add to resolve this issue. Im facing same issue as yours.

thanks in advance

**Comment by gschukin** [comment]
@sunil3s3 take a look at #1719

**Comment by sunil3s3** [comment]
thanks for quick response,. but its already present in my case. but still Im facing this error

   //Currently ceph doestn't return Last-Modified header for DLO manifest without any segments
        //Currently it affects all versions of ceph http://tracker.ceph.com/issues/15812
        if resp.Header.Get("Last-Modified") != "" {
                info.ServerLastModified = resp.Header.Get("Last-Modified")
                if info.LastModified, err = time.Parse(http.TimeFormat, info.ServerLastModified); err != nil {
                        return
                }
        }
        info.Hash = resp.Header.Get("Etag")
        return
}

**Comment by sunil3s3** [comment]
this is the image Im using

docker pull distribution/registry

this is how Im starting my registry with SWIFT object storage

docker run --restart=always --privileged=true -d --name pdit-registry1 -p 5000:5000 -e "REGISTRY_STORAGE=swift"
-e "REGISTRY_STORAGE_SWIFT_USERNAME=Storage-xxxxxx:xxxxx.Storageadmin" -e "REGISTRY_STORAGE_SWIFT_PASSWORD=xxxxxx"
-e "REGISTRY_STORAGE_SWIFT_AUTHURL=https://xxxxxxx.corp.com/auth/v1.0" -e "REGISTRY_STORAGE_SWIFT_CONTAINER=REGISTRY" distribution/registry

**Comment by gschukin** [comment]
Then you need to dump headers for this head request. 

What ceph version do you use?

**Comment by sunil3s3** [comment]
sorry I'm systemadmin and dont have much knowledge on python an tools.
Please let me know how to install ceph. is it through pip on Linux

**Comment by sunil3s3** [comment]
now I get it, ceph is the complete package distribution. 
Im using Oracle object storage which supports swift. I dont think ceph has to do any thing in my scenario.
Any more configs that I can check to get this work. Please help
