### ISSUE TITLE
no successful auth challenge for https

### ISSUE THREAD

**Issue by ysagon** [docker/distribution#870]
I'm trying to use the registry 

I'm using this image: 2a0a00a656a940a6a194840e1d996a951f770a763381fc55dffc83ea08616a94
I'm launching the registry like that:

    docker run -d -p 5000:5000 --restart=always --name registry \
      -v `pwd`/auth:/auth \
      -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
      -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
      -v `pwd`/certs:/certs \
      -e REGISTRY_LOG_LEVEL=debug \
      -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/ssl.crt \
      -e REGISTRY_HTTP_TLS_KEY=/certs/ssl.key \
      -e REGISTRY_STORAGE_S3_ACCESSKEY=AKIABLABLABLA \
      -e REGISTRY_STORAGE_S3_SECRETKEY=mysecret \
      -e REGISTRY_STORAGE_S3_REGION=eu-west-1 \
      -e REGISTRY_STORAGE_S3_BUCKET=my-repo \
      -e REGISTRY_STORAGE_S3_ENCRYPT=true \
      -e REGISTRY_STORAGE_S3_SECURE=true \
      -e REGISTRY_STORAGE_S3_V4AUTH=true \
      -e REGISTRY_STORAGE_S3_CHUNKSIZE= \
      registry:2

I have created first an htpasswd file:

    docker run --entrypoint htpasswd registry:2 -Bbn ysagon salut > auth/htpasswd

the stuff with the certs is ok. I don't know about the s3 part.

When I try to login from a docker client (1.8.1), I have the following message on stdout of the client:

    Error response from daemon: no successful auth challenge for https://registry.mydomain.com:5000/v2/ - errors: []

**Comment by RichardScothern** [comment]
Can you add
`-e REGISTRY_AUTH=htpasswd`
and retry.

If that doesn't work please post your config file and registry logs

**Comment by bausmeier** [comment]
I had the same issue and adding that environment variable solved it. Thanks.

**Comment by ysagon** [comment]
It'w working for me too, thanks.

The documentation here should be updated to reflect that:

**Comment by thaJeztah** [comment]
@ysagon if you're interested in contributing, and creating a pull request to fix that documentation; the Markdown file that's used to generate the documentation can be found in this repository; https://github.com/docker/distribution/blob/master/docs/deploying.md

**Comment by RichardScothern** [comment]
The documentation was fixed in master.  Closing.

**Comment by wputra** [comment]
still have this issue since https://docs.docker.com/registry/deploying/ still missing REGISTRY_AUTH env

**Comment by thaJeztah** [comment]
@wputra thanks for reporting; I don't think an update to the docs has been published yet

@moxiegirl if you're going to be pushing an intermediate update, I think this was fixed in https://github.com/docker/distribution/pull/865 (but there could be other fixes as well :relaxed:)

**Comment by moxiegirl** [comment]
@thaJeztah No new updates on the horizon this close to the next release.

**Comment by rajaneeshk1990** [comment]
Error response from daemon: no successful auth challenge for https://......dkr.ecr.ap-south-1.amazonaws.com/v2/ - errors: [basic auth attempt to https://........getting this type of error any solution
